### ISSUE TITLE
Add option to execute shell command after capture

### ISSUE THREAD

**Issue by OttoAllmendinger** [OttoAllmendinger/gnome-shell-screenshot#15]
This allows many different use cases: uploading, customized renaming etc

Arguments to shell command:

* filename
* position
* size

**Comment by mattgen88** [comment]
This would be useful for arbitrary uploading, a use case I need.

**Comment by isaaclw** [comment]
This would at least provide a solution for #64

**Comment by OttoAllmendinger** [comment]
Almost 4 years later :) https://github.com/OttoAllmendinger/gnome-shell-screenshot/commit/b722ff6ec46f2749763ac807b98a4a241f6dcc23

**Comment by OttoAllmendinger** [comment]
![image](https://user-images.githubusercontent.com/283533/102750172-a8578d00-4365-11eb-9c35-0094cba872ba.png)

**Comment by JohnPlayerSpecial** [comment]
I am using it to upload the screenshot to telegram 
`curl -F photo=@{f} https://api.telegram.org/bot<MY_BOT_TOKEN>/sendPhoto?chat_id=<MY_CHAT_ID>`

with success.

However since qrcode have become more popular and you often see them around I had an idea.
I want to use something like 

```zenity --info --text `zbarimg -q {f}```

zbarimg is a tool to decode qrcodes, while zenity is a basic gui to display the message (from zbarimg)

The problem is that I am not able to chain the two commands together.
I want to both  upload to telegram (I can do that as of now) and show the decoded qrcode string.
(if there is no qrcode in the screenshot zbarimg returns nothing)

I said ok, I can't do this so let's make a sh script.

```
FILENAME=$1
curl -F photo=@$FILENAME https://api.telegram.org/bot<TOKEN>/sendPhoto?chat_id=<chat_id>
zenity --info --text `zbarimg -q $FILENAME`  
```
and I am calling with 
`
sh /home/ub20/screenshot.sh {f}`

however this does not work, I get error exitcode=65280.

Any idea?
