### ISSUE TITLE
When previous save folder no longer exists

### ISSUE THREAD

**Issue by KSXGitHub** [OttoAllmendinger/gnome-shell-screenshot#60]
### Reproduction steps

1. Open Screenshot Tool settings
2. Go to 'Storage'
3. Change 'Save Location' to a folder
4. Delete that folder
5. Take a screenshot

### What happened

Nothing happened. No screenshot was taken.

### How to fix

1. Show error message
2. Create folders (may be nested, i.e. save folder is `abc/def/ghi` but delete `abc`)

**Comment by dansalvato** [comment]
This bug is also relevant when using `/` in the default filename setting, eg. `{Y}-{m}/{Y}-{m}-{d}_{H}-{M}-{S}`. The filename is correctly interpreted as `folder/file` and saves properly when the folder exists, but nothing happens if the folder doesn't exist. So, in my given example, screenshot saving would fail when a new month starts, and the Y-m folder for the new month doesn't yet exist.
